spring.application.name=eventbooking

# Server Port
server.port=8080

# DataSource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/eventbook
spring.datasource.username=postgres
spring.datasource.password=musinguziverelian23
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Jackson - Serialize LocalDateTime as ISO-8601 string (not array)
spring.jackson.datatype.datetime.write-dates-as-timestamps=false
